### ISSUE TITLE
Why is width/height not part of the blur hash encoding?

### ISSUE THREAD

**Issue by awhitford** [woltapp/blurhash#63]
Why is width & height of the original image not part of the blur hash encoding?  It seems that one  often needs to know that (or its aspect ratio) to paint the blur hash before the real image is faded in to replace it.

**Comment by Herohtar** [comment]
The dimension don't matter because you can render the decoded blur at any size you want, and you usually use a scaled-down version of the image to generate the blur anyway. Aspect ratio seems like it could potentially be useful information, but wouldn't you typically know the aspect ratio you need for most applications? I wouldn't think you would typically let the image dictate your layout.

**Comment by DagAgren** [comment]
Yes, usually you would provide that information separately along with the blurhash if you need it.
